- src/index.ts
- test/html.js
Hi taoqf,
I found a problem trying to parse html with custom element names,
if the element name has more than one dash in it.
The current HTML spec says a custom element must have **at least** one dash,
but also allows any number of dashes :)
https://html.spec.whatwg.org/multipage/custom-elements.html#valid-custom-element-name
PR if you want it :)
Andrew.
> Allow custom element names with multiple dashes

- src/index.ts
As per the readme, the parse function supports additional options which are not defined in its type, hence updating the type.
> updating the type of options in the parse function

- .gitignore
- src/nodes/html.ts
- test/html.js
It improves the behaviour of rawAttributes to work as before, so it doesn't return values wrapped in quotes.
It also fixed the issue of not adding quotes when the set value is number.
Added `getAttribute` to be the same as in browsers.
Bunch of behaviour fixes in tests to match behaviour of browsers.
> Add getAttribute, fix tests, fix rawAttributes, fix setAttribute when the value is number

- src/nodes/html.ts
- test/html.js
In HTML5s, self-closing are only foreign elements (from MathML and SVG namespace). What you call as unclosed elements is called void elements in HTML5 spec.
https://html.spec.whatwg.org/multipage/syntax.html#elements-2
> fix rendering of void elements (aka unclosed)

- src/nodes/html.ts
`he` is typed to provide named esm exports which is not strictly true altough it works with most bundlers. `he` is an UMD package that sets the `module.exports` to an object providing the exports. Some bundlers are only exposing `module.exports` as the default export and no named exports. All bundlers do expose `module.exports` as the default export.
This change allows `node-html-parser` to be compatible with all bundlers by destructering the default export and no using any named exports.
> fix: use default export from he with destructering

- .eslintrc.json
- src/nodes/html.ts
- test/emptyattribute.js
- test/html.js
```js
const { parse } = require('node-html-parser')
var root = parse(`\
<html>
<div class="main">yay</div>
</html>
`);
```
```js
root.querySelector('div.main').innerHTML = 'innerHTML setter was here';
console.log(root.toString());
var result = `\
<html>
<div class="main">innerHTML setter was here</div>
</html>
`;
```
```js
root.querySelector('div.main').replaceWith('<pre>replaceWith was here</pre>');
console.log(root.toString());
var result = `\
<html>
<pre>replaceWith was here</pre>
</html>
`;
```
use case: transform custom elements
<details>
```js
var root = parse(`\
<html>
<some-custom-element class="main">yay</some-custom-element>
</html>
`);
root.querySelectorAll('some-custom-element').forEach(node => {
//const nodeNew = parse('<div></div>') // not working, we cannot change root node …
```
> add node.replaceWith + add innerHTML setter 

- src/nodes/html.ts
- test/112.js
Fixed a problem where the `this.id (string)` was sometimes `undefined`.
I used the behavior of the chrome browser as a reference.
> Fix id handling

- package.json
Some bundlers use the 'sideEffects' key in a package's `package.json` as a hint that the package does not have impactful side effects when the module is imported
> Add 'sideEffects: false' bundler hint in package.json

- src/nodes/html.ts
- test/quoteattributes.js
Currently double quotes (") are not escaped in attribute values causing those attributes not to be set correctly.
This commit replaces double quotes with `&quot;`.
> Fixes #62 - Escape double quotes in attribute values

- src/nodes/html.ts
The purpose of `nextElementSibling` is to return an `HTMLElement`, not any kind of `Node` ([DOM standard](https://dom.spec.whatwg.org/#dom-nondocumenttypechildnode-nextelementsibling)).
The `.tsconfig` disables strict null-checking, so I forgo adding the `null` return type.
> nextElementSibling returns an HTMLElement

- src/nodes/html.ts
- src/nodes/text.ts
- test/html.js
The following PR takes a holistic approach to mitigating issue #115 by implementing HTML-specific trim functionality, where necessary. Its aim is to provide a more accurate correction for the `trim()` issue by replicating trim, while explicitly preserving only single leading or trailing non-breaking whitespace, where present.
In addition to the already corrected area (`structuredText`) a second affected area was found.
The purpose of `HTMLElement#removeWhitespace` is to remove unnecessary whitespace nodes and otherwise cleanup the text. To do this, it calls `trim()` on `TextNode` rawText. Unfortuntately, this is too greedy.
Trim rightly removes repeating spaces, tabs, and line-breaks, which are often simply junk from multi-line HTML formatting. Unfortunately, it also removes legitimate, …
> fix issue #115

- package.json
allow to install from source
for example 
`npm install 'git+https://github.com/milahu/node-html-parser#add-source-location-to-nodes'`
to use `node._source.start` and `node._source.end`
> package.json: add prepare script

- package.json
`css-what` which is a dependency of `css-select` have a vulnerability is versions prior to 5.0.1. `css-select` seem to have used ^5.0.0 of `css-what` since version 4 (https://github.com/fb55/css-select/blob/v4.0.0/package.json#L25), so I bumped the dependency here to the latest of `css-select` and all tests seem to pass so hopefully all is good.
If anyone think of any more testing needed part from existing test passing, I'll be happy to assist.
> Bump css-select to ^4.1.3 to resolve https://npmjs.com/advisories/1754

- README.md
- package.json
- src/nodes/comment.ts
- src/nodes/html.ts
- src/nodes/node.ts
- src/nodes/text.ts
- test/node-ranges.js
- test/parse.js
It turns out that other AST parsers _do_ create a `TextNode` for all whitespace (see https://astexplorer.net) The only which does not is the parser for angular templates, which it likely does because it's used in a very narrow context.
The issue ended up being that `node-html-parser` actually does create a `TextNode` for whitespace, but there were some cases in which that was failing to happen. This caused the behaviour to differ from other parsers and is the root of the issue laid out in #137.
- Added `range` property to nodes
- Fixed whitespace not being created issue (solves #137 & #126)
- Cleaned up parser code to make it understandable and slightly more efficient
- Added comprehensive test for node ranges
- Added basic whitespace parser test
*v4.1.0*
Because a feature was added, I …
> feat: Add range to nodes and fix whitespace issue (fixes #137)

- package.json
> Add `exports.types` to `package.json` to fix typing issues under ESM

- src/nodes/html.ts
- test/tests/html.js
The HTML attribute regex does not capture attributes that start with an `@` correctly. You might run into this when working with shorthand event handlers in micro-frameworks such as Alpine.js or petite-vue. This fixes that.
e.g. `@click="doSmt()"` yields attribute `click` with a value of `doSmt()`. With the current regex, `rawAttrs` does not contain the right value (it contains `click` without the `@`). This PR fixes that.
https://github.com/taoqf/node-html-parser/blob/05f474f751a93ea30590733380263d2f669a3987/src/nodes/html.ts#L690
> Added support for shorthand event handler syntax

- src/nodes/html.ts
Update the return of the closest function to ensure that we return either a HTMLElement or null. 
As the MDN spec for the .closest function states, the return type is _'The closest ancestor Element or itself, which matches the selectors. If there are no such element, null'_ 
This means it should be an actual Element type and not a node. This solves a wider issue with TS that prevents users from chaining `querySelector` and calls to `closest`.
This provides a much more native behaviour akin to what is actually experienced within the browser environment.
> Chore: Update the return of the closest function

- src/nodes/html.ts
- test/tests/html.js
- test/tests/issues/224.js
The HTML specification nominally does not allow duplicate attributes in a tag (see [13.1.2.3](https://html.spec.whatwg.org/multipage/syntax.html#attributes-2), last paragraph). However, browsers fail graciously when encountering such a tag, respecting only the first tag present and discarding subsequent duplicates (Safari 17614.1.25.9.10, Chrome 109.0.5414.119).
Bring node-html-parser in alignment with that convention, respecting the first attribute and ignoring subsequent matches.
> First attribute in a tag wins

- src/nodes/html.ts
Happy for this to just be a `docs` commit instead if you'd rather not release this change on its own.
> fix: Fixed typo in JSDoc for HTMLElement `structure` method

- package.json
this was originally added in 366d048efddc30ec8411f7624841a596aaa8798d (#125)
and removed in 3140baa26f51bea030ea6679e6eeb038565c443e (#161)
the purpose of the `npm run build` prepare script
is to allow "install from git" which is currently broken
`cd test && yarn install` is not needed for "install from git"
tested with
```
pnpm i 'github:taoqf/node-html-parser#cd3fcd7ba3081c7b546351a282de04596fab502c'
```
> restore the prepare script "npm run build"

- README.md
- src/nodes/html.ts
Hi,
This is the greatest tool I've ever found. But some types flaw with TypeScript.
Following methods in `HTMLElement` can return `null`, but do not declare correct return types.
- `getElementById`
- `querySelector` (in README only)
- `nextSibling`
- `nextElementSibling` 
- `previousSibling`
- `previousElementSibling`
Following methods in `HTMLElement` can return `undefined`, but do not declare correct return types. Actually these should follow the [web API](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement) and return `null`, but I did not change them to prevent breaking the backward compability.
- `getAttribute` (in README and jsdocs only)
- `firstChild`
- `lastChild`
> fix: nullable return types of HTMLElement

- README.md
Two parsing options are missing. That commit adds them to the README file.
> docs(readme): add missing parse options

- README.md
- src/nodes/html.ts
- test/tests/html.js
Hi,
First of all, thanks for writing this library, it's a really clever yet simple DOM abstraction!
I implemented some methods that I felt were missing from the `HTMLElement`. They are commonly used in the actual [DOM](https://developer.mozilla.org/en-US/docs/Web/API/Element) and thus provide better compatibility with other backend DOM abstractions as well (in my case, I switched from deno-dom to node-html-parser, and I had to shim some of these).
- `get children()` (only `HTMLElement` children)
- `get firstElementChild()`
- `get lastElementchild()`
- `get childElementCount()`
- `before(...nodes)`
- `after(...nodes)`
- `prepend(...nodes)`
- `append(...nodes)`
The last four are now the base operations. `insertAdjacentHTML` and `appendChild` use them and they are tested accordingly.
README …
> Implement more getters and methods on HTMLElement, in accordance with the DOM spec

- src/nodes/html.ts
- test/tests/attributes-with-dots.js
This adds support for attributes containing dots (`.`) in names. 
**Note**: there is a bunch of formatting updates due to `prettier`, I suspect. It seems like some of this code was not properly formatted before even though there is a `.prettierrc` present
> Correctly handle attributes with dots in names
